### ISSUE TITLE
About the version format of tag

### ISSUE THREAD

**Issue by lynin** [alphadose/itogami#1]
hi, I see that you have two tags, `0.1.0` and `0.2.0` respectively, but this seems to be inconsistent with the version number specification of go modules. I used `go get github.com/alphadose/itogami@0.2.0`, pointing to `v0.0.0-20220617064735-3fb829d9078f`. The implication is whether the prefix `v` is missing, such as `v0.2.0`

**Comment by alphadose** [comment]
@lynin you are right, I didnt know about the `v` factor https://github.com/golang/go/issues/34512

I have released a new version with the proper semantics https://github.com/alphadose/itogami/releases/tag/v0.3.0

pls check if this one is working for you or not

also thanks a lot for pointing out this major issue, I got to learn something interesting today
